# The MIT License (MIT)
#
# Copyright (c) 2024 Aliaksei Bialiauski
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
---
name: cluster
'on':
  workflow_dispatch:
    inputs:
      out:
        description: "Output folder"
        required: true
permissions: write-all
jobs:
  generate:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - uses: abatilo/actions-poetry@v3
        with:
          poetry-version: "1.8.3"
      - uses: extractions/setup-just@v2
        with:
          just-version: "1.30.1"
      - name: Create
        run: |
          mkdir -p "clustered/${{ inputs.out }}"
          {
            just install
            just cluster "../clustered/${{ inputs.out }}"
            just clusterstat "../clustered/${{ inputs.out }}" "../${{ inputs.out }}.txt"
          } 2>&1 | tee -a cluster.log
          cp "cluster.log" "clustered/${{ inputs.out }}"
      - uses: JamesIves/github-pages-deploy-action@v4.7.1
        with:
          branch: clusters
          folder: clustered
          clean: false
        if: github.ref == 'refs/heads/master'
