# The MIT License (MIT)
#
# Copyright (c) 2024 Aliaksei Bialiauski
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
---
name: collect
'on':
  workflow_dispatch:
    inputs:
      start:
        description: "Collect repositories created from, in YYYY-MM-D format"
        required: true
      end:
        description: "Collect repositories created up to, in YYYY-MM-DD format"
        required: false
        default: "2024-05-01"
      out:
        description: "Output directory"
        required: true
permissions: write-all
env:
  PATS: pats.txt
jobs:
  collect:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - uses: abatilo/actions-poetry@v3
        with:
          poetry-version: "1.8.3"
      - uses: extractions/setup-just@v2
        with:
          just-version: "1.30.1"
      - name: Collect
        run: |
          just install
          poetry install
          echo "${{ secrets.COLLECT_TOKEN_1 }}" >> "$PATS"
          just collect "collection/${{ inputs.out }}" "${{ inputs.start }}" \
            "${{ inputs.end }}" "repos" "${{ secrets.GITHUB_TOKEN }}"
          just filter "repos-with-pulls.csv" "after-filter.csv"
          just extract "after-filter.csv" "after-extract.csv"
          just maven "after-extract.csv" "${{ secrets.GITHUB_TOKEN }}" \
            "after-maven.csv"
          cp "repos.csv" "collection/${{ inputs.out }}"
          cp "repos-with-pulls.csv" "collection/${{ inputs.out }}"
          cp "after-filter.csv" "collection/${{ inputs.out }}"
          cp "after-extract.csv" "collection/${{ inputs.out }}"
          cp "after-maven.csv" "collection/${{ inputs.out }}"
      - uses: JamesIves/github-pages-deploy-action@v4.6.8
        with:
          branch: collect
          folder: collection
          clean: false
        if: github.ref == 'refs/heads/master'
