# The MIT License (MIT)
#
# Copyright (c) 2024 Aliaksei Bialiauski
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
---
name: collect
'on':
  workflow_dispatch:
    inputs:
      start:
        description: "Start collection from date in YYYY-MM-DD format"
        required: true
permissions: write-all
env:
  PATS: pats.txt
jobs:
  collect:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Install ghminer
        run: |
          npm install -g ghminer@0.0.6
      - name: Collect
        run: |
          echo "${{ secrets.COLLECT_TOKEN_1 }}" >> "$PATS"
          mkdir -p collection
          ghminer --query "stars:>10 language:java size:>=20 mirror:false template:false" \
            --start "${{ inputs.start }}" --end "2024-05-01" --tokens "$PATS" \
              --filename "repos"
          cp "repos.csv" collection
      - uses: JamesIves/github-pages-deploy-action@v4.6.1
        with:
          branch: collect
          folder: collection
          clean: false
        if: github.ref == 'refs/heads/master'
