# The MIT License (MIT)
#
# Copyright (c) 2024 Aliaksei Bialiauski
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
---
name: collect
'on':
  workflow_dispatch:
    inputs:
      start:
        description: "Collect repositories created from, in YYYY-MM-D format"
        required: true
      end:
        description: "Collect repositories created up to, in YYYY-MM-DD format"
        required: false
        default: "2024-05-01"
      out:
        description: "Output directory"
        required: true
      clean:
        description: "Clean branch before uploading files"
        required: true
        type: choice
        default: false
        options:
          - false
          - true
permissions: write-all
env:
  PATS: pats.txt
jobs:
  collect:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - uses: abatilo/actions-poetry@v3
        with:
          poetry-version: "1.8.3"
      - uses: extractions/setup-just@v2
        with:
          just-version: "1.30.1"
      - name: Collect
        run: |
          echo "${{ secrets.COLLECT_TOKEN_1 }}" >> "$PATS"
          TOKEN="${{ secrets.GITHUB_TOKEN }}"
          {
            just install
            poetry install
            just collect "collection/${{ inputs.out }}" "${{ inputs.start }}" \
              "${{ inputs.end }}" "repos"
            just pulls "../repos.csv" "$TOKEN" "../repos-with-pulls.csv"
            just filter "../repos-with-pulls.csv" "../after-filter.csv"
            just mcw "../after-filter.csv" "../after-mcw.csv"
            just swc "../after-mcw.csv" "../after-swc.csv"
            just extract "../after-swc.csv" "../after-extract.csv"
            just snippets "../after-extract.csv" "../after-snippets.csv"
            just maven "../after-snippets.csv" "../after-maven.csv" "$TOKEN"
            just junit "../after-maven.csv" "../after-junit.csv" "$TOKEN"
            just lens "../after-junit.csv" "../after-lens.csv"
            just links "../after-lens.csv" "../after-links.csv"
            just final "../after-links.csv" "../final.csv"
          } 2>&1 | tee -a collect.log
          sed -i "s|$TOKEN|REDACTED|g" collect.log
          mkdir -p "collection/${{ inputs.out }}/steps"
          cp "repos.csv" "collection/${{ inputs.out }}/steps/"
          cp "repos-with-pulls.csv" "collection/${{ inputs.out }}/steps/"
          cp "after-filter.csv" "collection/${{ inputs.out }}/steps/"
          cp "after-mcw.csv" "collection/${{ inputs.out }}/steps/"
          cp "after-swc.csv" "collection/${{ inputs.out }}/steps/"
          cp "after-extract.csv" "collection/${{ inputs.out }}/steps/"
          cp "after-snippets.csv" "collection/${{ inputs.out }}/steps/"
          cp "after-maven.csv" "collection/${{ inputs.out }}/steps/"
          cp "after-junit.csv" "collection/${{ inputs.out }}/steps/"
          cp "after-lens.csv" "collection/${{ inputs.out }}/steps/"
          cp "after-links.csv" "collection/${{ inputs.out }}/steps/"
          cp "collect.log" "collection/${{ inputs.out }}"
          cp "final.csv" "collection/${{ inputs.out }}"
      - uses: JamesIves/github-pages-deploy-action@v4.6.8
        with:
          branch: collect
          folder: collection
          clean: ${{ inputs.clean }}
        if: github.ref == 'refs/heads/master'
